In [1]:
%matplotlib inline


What is PyTorch?
================

It’s a Python-based scientific computing package targeted at two sets of
audiences:

-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

Getting Started
---------------

Tensors
^^^^^^^

Tensors are similar to NumPy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.



In [2]:
from __future__ import print_function
import torch

Construct a 5x3 matrix, uninitialized:



In [3]:
x = torch.empty(5, 3)
print(x)

tensor([[1.8567e-01, 7.5553e+28, 5.2839e-11],
        [7.5018e+28, 2.5460e-12, 3.8473e-11],
        [7.1428e+31, 1.7466e+19, 1.4585e-19],
        [4.4721e+21, 7.2070e+22, 4.7428e+30],
        [7.9801e-10, 2.5171e-12, 1.4586e-19]])


Construct a randomly initialized matrix:



In [4]:
x = torch.rand(5, 3)
print(x)

tensor([[0.6654, 0.0576, 0.7416],
        [0.6273, 0.1948, 0.1303],
        [0.9041, 0.3271, 0.3643],
        [0.8921, 0.6249, 0.5973],
        [0.3903, 0.3812, 0.3961]])


Construct a matrix filled zeros and of dtype long:



In [5]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Construct a tensor directly from data:



In [6]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


or create a tensor based on an existing tensor. These methods
will reuse properties of the input tensor, e.g. dtype, unless
new values are provided by user



In [7]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-2.1041, -2.4188,  0.2055],
        [-0.1849, -1.8972,  1.3984],
        [-0.1104, -0.1538, -0.8232],
        [ 0.1861,  0.1937,  0.4412],
        [-2.2957, -1.5336, -1.0118]])


Get its size:



In [8]:
print(x.size())

torch.Size([5, 3])


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` is in fact a tuple, so it supports all tuple operations.</p></div>

Operations
^^^^^^^^^^
There are multiple syntaxes for operations. In the following
example, we will take a look at the addition operation.

Addition: syntax 1



In [9]:
y = torch.rand(5, 3)
print(x + y)

tensor([[-1.1213, -1.7732,  0.6379],
        [ 0.3205, -1.7802,  2.0210],
        [ 0.8117,  0.0691, -0.5537],
        [ 0.4828,  0.9856,  0.7368],
        [-2.1787, -1.3769, -0.5595]])


Addition: syntax 2



In [10]:
print(torch.add(x, y))

tensor([[-1.1213, -1.7732,  0.6379],
        [ 0.3205, -1.7802,  2.0210],
        [ 0.8117,  0.0691, -0.5537],
        [ 0.4828,  0.9856,  0.7368],
        [-2.1787, -1.3769, -0.5595]])


Addition: providing an output tensor as argument



In [11]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-1.1213, -1.7732,  0.6379],
        [ 0.3205, -1.7802,  2.0210],
        [ 0.8117,  0.0691, -0.5537],
        [ 0.4828,  0.9856,  0.7368],
        [-2.1787, -1.3769, -0.5595]])


Addition: in-place



In [12]:
# adds x to y
y.add_(x)
print(y)

tensor([[-1.1213, -1.7732,  0.6379],
        [ 0.3205, -1.7802,  2.0210],
        [ 0.8117,  0.0691, -0.5537],
        [ 0.4828,  0.9856,  0.7368],
        [-2.1787, -1.3769, -0.5595]])


<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an ``_``.
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>

You can use standard NumPy-like indexing with all bells and whistles!



In [13]:
print(x[:, 1])

tensor([-2.4188, -1.8972, -0.1538,  0.1937, -1.5336])


Resizing: If you want to resize/reshape tensor, you can use ``torch.view``:



In [14]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


If you have a one element tensor, use ``.item()`` to get the value as a
Python number



In [15]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.1422])
0.1422128528356552


**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described
  `here <https://pytorch.org/docs/torch>`_.

NumPy Bridge
------------

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory
locations (if the Torch Tensor is on CPU), and changing one will change
the other.

Converting a Torch Tensor to a NumPy Array
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



In [16]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [17]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value.



In [18]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


Converting NumPy Array to Torch Tensor
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
See how changing the np array changed the Torch Tensor automatically



In [19]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

CUDA Tensors
------------

Tensors can be moved onto any device using the ``.to`` method.



In [20]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([1.1422], device='cuda:0')
tensor([1.1422], dtype=torch.float64)
